name: Integration Tests
 
env:
  DB_HOST: ${{ secrets.DATABASE_HOSTNAME }}
  DB_USER: ${{ secrets.DATABASE_USER }}
  DB_PASS: ${{ secrets.DATABASE_PASSWORD }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_NAME: ${{ secrets.DATABASE }}
 
on:
  pull_request:
    branches:
      - main
 
jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name : Install MySQL
        run: |
          sudo apt-get update
          sudo systemctl start mysql.service
          sudo mysql --user=${DB_USER} --password=${DB_PASS} -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"
 
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
 
      - name: Install Dependencies
        run: npm install
 
      - name: Run Tests
        run: npm test